# Generated by Django 3.2.6 on 2021-10-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTickets', '0002_busarrangement_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='busarrangement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busarrangement',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='busarrangement',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='busarrangement',
            name='ticket_total',
            field=models.SmallIntegerField(null=True, unique=True),
        ),
    ]
