# Generated by Django 3.2.6 on 2021-10-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTickets', '0003_auto_20211028_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busarrangement',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='busarrangement',
            name='ticket_total',
            field=models.SmallIntegerField(null=True),
        ),
    ]
