# Generated by Django 3.2.6 on 2021-10-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTickets', '0004_auto_20211028_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='busesline',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
