# Generated by Django 3.2.6 on 2021-10-30 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookTickets', '0005_busesline_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='busarrangement',
            name='Buses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='BookTickets.buses'),
        ),
    ]
