# Generated by Django 3.2.6 on 2021-11-10 11:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookTickets', '0007_auto_20211108_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='uploads/reports/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_create_report', to=settings.AUTH_USER_MODEL)),
                ('user_is_reported', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_is_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('creator', 'user_is_reported')},
            },
        ),
    ]
