# Generated by Django 3.2.6 on 2021-12-18 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookTickets', '0008_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentBusArrangementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('busarrangement_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmt_busarrangement', to='BookTickets.busarrangement')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
